name: Continuous Build analysis

on:
  push:
    branches:
      - main

jobs:

  build:
    name: build development branch
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven Build & Sonar analysis
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar