name: Continuous Branch Analysis

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build prod branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NPM install
        run: npm install

      - name: NPM Build
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t croissantage-front .

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: univ-smb-m1-isc-2022/croissantage-front/master
          tags: latest